version: "3.8"
services:
  backend:
    image: "murtuza47/springboot-react-fullstack:15.2.2023.20.22.8"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev